### ISSUE TITLE
文字列比較におけるバグ

### ISSUE THREAD

**Issue by sakaro01** [Takatymo/Zone#2]
views.pyのsearchメソッドにて    if result['status'] is 'OK':　が追加されていました。
この条件式の追加自体は問題ないですが、この条件ではどうなってもTrueにはなりません。
pythonで文字列の比較を行うなら「is」ではなく「==」です。

pythonの「is」と「==」の違いおよび基本データ型と参照型に関して調べてみるといいと思います。

**Comment by Takatymo** [comment]
ご指摘の問題を修正しました。
これからも勉強して行きます。
